import type { LanguageConfig } from './types.js';

export const DEFAULT_LANGUAGES: LanguageConfig[] = [
    {
        id: 'typescript',
        name: 'TypeScript',
        extensions: ['.ts', '.tsx', '.mts', '.cts'],
        shebangPatterns: [],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-typescript',
    },
    {
        id: 'javascript',
        name: 'JavaScript',
        extensions: ['.js', '.jsx', '.mjs', '.cjs'],
        shebangPatterns: [/^#!.*node/],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-javascript',
    },
    {
        id: 'python',
        name: 'Python',
        extensions: ['.py', '.pyi', '.pyx'],
        shebangPatterns: [/^#!.*python/],
        commentStyle: { line: '#' },
        treeSitterGrammar: 'tree-sitter-python',
    },
    {
        id: 'java',
        name: 'Java',
        extensions: ['.java'],
        shebangPatterns: [],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-java',
    },
    {
        id: 'go',
        name: 'Go',
        extensions: ['.go'],
        shebangPatterns: [],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-go',
    },
    {
        id: 'rust',
        name: 'Rust',
        extensions: ['.rs'],
        shebangPatterns: [],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-rust',
    },
    {
        id: 'cpp',
        name: 'C++',
        extensions: ['.cpp', '.cc', '.cxx', '.hpp', '.hxx', '.hh', '.h'],
        shebangPatterns: [],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-cpp',
    },
    {
        id: 'csharp',
        name: 'C#',
        extensions: ['.cs'],
        shebangPatterns: [],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-c-sharp',
    },
    {
        id: 'php',
        name: 'PHP',
        extensions: ['.php', '.phtml'],
        shebangPatterns: [],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-php',
    },
    {
        id: 'ruby',
        name: 'Ruby',
        extensions: ['.rb', '.rake', '.gemspec'],
        shebangPatterns: [/^#!.*ruby/],
        commentStyle: { line: '#' },
        treeSitterGrammar: 'tree-sitter-ruby',
    },
    {
        id: 'swift',
        name: 'Swift',
        extensions: ['.swift'],
        shebangPatterns: [],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-swift',
    },
    {
        id: 'kotlin',
        name: 'Kotlin',
        extensions: ['.kt', '.kts'],
        shebangPatterns: [],
        commentStyle: { line: '//', block: ['/*', '*/'] },
        treeSitterGrammar: 'tree-sitter-kotlin',
    },
];